"""0004_transaction: transaction table

Revision ID: 0004_transaction
Revises: 0003_hero
Create Date: 2026-04-27 12:04:00

Реализует §5.2 transaction. Партиционирование убрано из MVP — таблица
обычная (один сегмент), PRIMARY KEY (id). Возврат к партиционированию
по ``created_at`` запланирован после ~10M+ строк (см. DATABASE.md §14).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_transaction"
down_revision: str | None = "0003_hero"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.execute(
        sa.DDL(
            """
            CREATE TABLE "transaction" (
                id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                profile_id      BIGINT NOT NULL,
                type            SMALLINT NOT NULL,
                amount          BIGINT NOT NULL,
                balance_after   BIGINT NOT NULL,
                ref             JSONB,
                idempotency_key UUID,
                created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT fk_transaction_profile FOREIGN KEY (profile_id)
                    REFERENCES profile(id),
                CONSTRAINT ck_transaction_type CHECK (type BETWEEN 0 AND 22),
                CONSTRAINT uq_transaction_idempotency UNIQUE (idempotency_key)
            );
            """
        )
    )

    op.execute(
        sa.DDL(
            """
            CREATE INDEX ix_transaction_profile_created
                ON "transaction" (profile_id, created_at DESC);
            """
        )
    )
    op.execute(
        sa.DDL(
            """
            CREATE INDEX ix_transaction_type_created
                ON "transaction" (type, created_at DESC);
            """
        )
    )
    op.execute(
        sa.DDL(
            """
            CREATE INDEX ix_transaction_ref_run
                ON "transaction" ((ref->>'run_id'))
                WHERE ref ? 'run_id';
            """
        )
    )


def downgrade() -> None:
    op.execute('DROP TABLE IF EXISTS "transaction" CASCADE;')
