"""0004_transaction: transaction table (partitioned by month)

Revision ID: 0004_transaction
Revises: 0003_hero
Create Date: 2026-04-27 12:04:00

Реализует §5.2 transaction с партиционированием по месяцам начиная с 2026-04.
SA не поддерживает PARTITION BY в ORM-DDL — используем op.execute().

Стартовые партиции на 4 месяца вперёд. Cron создания будущих партиций
будет в Phase 1 (Arq task), см. DATABASE.md §14.3.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0004_transaction"
down_revision: str | None = "0003_hero"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Сама таблица — partitioned. SA create_table не умеет PARTITION BY,
    # делаем вручную.
    op.execute(
        """
        CREATE TABLE "transaction" (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
            profile_id   BIGINT NOT NULL,
            type         SMALLINT NOT NULL,
            amount       BIGINT NOT NULL,
            balance_after BIGINT NOT NULL,
            ref          JSONB,
            idempotency_key TEXT,
            created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
            PRIMARY KEY (id, created_at),
            CONSTRAINT fk_transaction_profile FOREIGN KEY (profile_id)
                REFERENCES profile(id),
            CONSTRAINT ck_transaction_type CHECK (type BETWEEN 0 AND 22)
        ) PARTITION BY RANGE (created_at);
        """
    )

    # Уникальный индекс по idempotency_key (на партиционированной таблице
    # уникальность должна включать ключ партиционирования, но idempotency_key
    # обычно UUID и уникален глобально — ставим UNIQUE INDEX без партиционного ключа
    # в каждой партиции отдельно. Для MVP — INDEX без UNIQUE на parent +
    # ON CONFLICT защита на app-уровне).
    op.execute(
        """
        CREATE INDEX uq_transaction_idempotency
            ON "transaction" (idempotency_key)
            WHERE idempotency_key IS NOT NULL;
        """
    )

    op.execute(
        """
        CREATE INDEX ix_transaction_profile_created
            ON "transaction" (profile_id, created_at DESC);
        """
    )
    op.execute(
        """
        CREATE INDEX ix_transaction_type_created
            ON "transaction" (type, created_at DESC);
        """
    )
    op.execute(
        """
        CREATE INDEX ix_transaction_ref_run
            ON "transaction" ((ref->>'run_id'))
            WHERE ref ? 'run_id';
        """
    )

    # Стартовые партиции (4 месяца вперёд от 2026-04)
    for year, month in [
        (2026, 4),
        (2026, 5),
        (2026, 6),
        (2026, 7),
        (2026, 8),
    ]:
        next_year = year if month < 12 else year + 1
        next_month = month + 1 if month < 12 else 1
        op.execute(
            f"""
            CREATE TABLE transaction_{year}_{month:02d}
                PARTITION OF "transaction"
                FOR VALUES FROM ('{year}-{month:02d}-01')
                TO ('{next_year}-{next_month:02d}-01');
            """
        )


def downgrade() -> None:
    # Drop partitions сначала, потом parent — но DROP TABLE parent
    # каскадно удалит партиции. Достаточно одного DROP.
    op.execute('DROP TABLE IF EXISTS "transaction" CASCADE;')
