"""0003_hero: hero table

Revision ID: 0003_hero
Revises: 0002_referral
Create Date: 2026-04-27 12:03:00

Реализует §4.1 hero.

CREATE TABLE через ``op.execute`` raw SQL — SA ``sa.text()`` парсит ``:0``
в JSON-литералах как bind-параметр (``invalid input syntax for type json,
Token "NULL" is invalid``).
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0003_hero"
down_revision: str | None = "0002_referral"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ``sa.DDL`` вместо строки — иначе ``op.execute`` оборачивает в ``sa.text``
    # и парсит ``:0`` в JSON-литералах как bind-параметры.
    op.execute(sa.DDL("""
        CREATE TABLE hero (
            id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            profile_id    BIGINT NOT NULL,
            class         SMALLINT NOT NULL,
            name          TEXT NOT NULL,
            level         INTEGER NOT NULL DEFAULT 1,
            xp            BIGINT NOT NULL DEFAULT 0,
            unspent_points JSONB NOT NULL DEFAULT '{"stat":0,"skill":0}'::jsonb,
            base_stats     JSONB NOT NULL DEFAULT '{"str":10,"dex":5,"int":3}'::jsonb,
            passives       JSONB NOT NULL DEFAULT '[]'::jsonb,
            active_skills  JSONB NOT NULL DEFAULT '[]'::jsonb,
            created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
            deleted_at    TIMESTAMPTZ,
            CONSTRAINT fk_hero_profile FOREIGN KEY (profile_id)
                REFERENCES profile (id) ON DELETE CASCADE,
            CONSTRAINT ck_hero_class CHECK (class BETWEEN 0 AND 2),
            CONSTRAINT ck_hero_level CHECK (level BETWEEN 1 AND 100),
            CONSTRAINT ck_hero_xp CHECK (xp >= 0),
            CONSTRAINT ck_hero_name_len CHECK (char_length(name) BETWEEN 3 AND 20),
            CONSTRAINT ck_hero_unspent_points CHECK (
                jsonb_typeof(unspent_points) = 'object'
                AND jsonb_typeof(unspent_points->'stat') = 'number'
                AND jsonb_typeof(unspent_points->'skill') = 'number'
                AND (unspent_points->>'stat')::int >= 0
                AND (unspent_points->>'skill')::int >= 0
            )
        );
    """))
    # MVP: один hero определённого класса на profile
    op.create_index(
        "uq_hero_profile_class",
        "hero",
        ["profile_id", "class"],
        unique=True,
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_hero_profile",
        "hero",
        ["profile_id"],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index(
        "ix_hero_level",
        "hero",
        ["level"],
        postgresql_where=sa.text("deleted_at IS NULL"),
    )
    op.execute(
        """
        CREATE TRIGGER trg_hero_updated_at
        BEFORE UPDATE ON hero
        FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
        """
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_hero_updated_at ON hero;")
    op.execute("DROP TABLE IF EXISTS hero CASCADE;")
