"""0007_items: §6 item_base + affix_definition + item

Revision ID: 0007_items
Revises: 0006_idempotency_keys
Create Date: 2026-04-28 12:07:00

Реализует DATABASE.md §6 целиком:

* ``item_base`` (reference) — статичный каталог базовых типов
* ``affix_definition`` (reference) — все возможные аффиксы для генерации
* ``item`` — экземпляры предметов юзеров со snapshot affixes JSONB

Snapshot affixes: при дропе сохраняем ``[{id,value,t,vmin,vmax}]`` —
балансные правки ``affix_definition`` не задним числом не ломают существующие
предметы (PoE/D2 практика, см. §6.3.1).

FK ``item.escrow_run_id → dungeon_runs(id)`` отложена до миграции 0008
(``dungeon_runs`` ещё не существует). Колонка ``escrow_run_id UUID`` создана,
FK добавится в 0008.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0007_items"
down_revision: str | None = "0006_idempotency_keys"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ===== §6.1 item_base =====
    op.execute(
        sa.DDL(
            """
            CREATE TABLE item_base (
                id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                kind          TEXT         NOT NULL,
                slot          SMALLINT     NOT NULL,
                min_ilvl      INT          NOT NULL DEFAULT 1,
                base_stats    JSONB        NOT NULL,
                is_two_handed BOOLEAN      NOT NULL DEFAULT false,
                created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
                CONSTRAINT uq_item_base_kind UNIQUE (kind),
                CONSTRAINT ck_item_base_slot CHECK (slot BETWEEN 0 AND 5),
                CONSTRAINT ck_item_base_min_ilvl CHECK (min_ilvl >= 1)
            );
            """
        )
    )
    op.execute(
        sa.DDL("CREATE INDEX ix_item_base_slot ON item_base (slot);")
    )

    # ===== §6.2 affix_definition =====
    op.execute(
        sa.DDL(
            """
            CREATE TABLE affix_definition (
                id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                affix_type       SMALLINT  NOT NULL,
                mod_group        TEXT      NOT NULL,
                min_ilvl         INT       NOT NULL DEFAULT 1,
                tier             INT       NOT NULL DEFAULT 1,
                weight           INT       NOT NULL DEFAULT 100,
                applicable_slots JSONB     NOT NULL,
                tags             JSONB     NOT NULL DEFAULT '[]'::jsonb,
                spawn_weights    JSONB,
                mod_type         TEXT      NOT NULL,
                value_min        INT       NOT NULL,
                value_max        INT       NOT NULL,
                created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
                CONSTRAINT uq_affix_def_natural UNIQUE (mod_group, mod_type, tier),
                CONSTRAINT ck_affix_type        CHECK (affix_type BETWEEN 0 AND 2),
                CONSTRAINT ck_affix_value_range CHECK (value_min <= value_max),
                CONSTRAINT ck_affix_tier        CHECK (tier BETWEEN 1 AND 10),
                CONSTRAINT ck_affix_weight_pos  CHECK (weight > 0),
                CONSTRAINT ck_affix_min_ilvl    CHECK (min_ilvl >= 1)
            );
            """
        )
    )
    op.execute(
        sa.DDL(
            """
            CREATE INDEX ix_affix_def_type_ilvl
                ON affix_definition (affix_type, min_ilvl);
            """
        )
    )
    op.execute(
        sa.DDL(
            "CREATE INDEX ix_affix_def_modgroup ON affix_definition (mod_group);"
        )
    )
    op.execute(
        sa.DDL(
            """
            CREATE INDEX ix_affix_def_tags
                ON affix_definition USING gin (tags);
            """
        )
    )
    op.execute(
        sa.DDL(
            """
            CREATE INDEX ix_affix_def_slots
                ON affix_definition USING gin (applicable_slots);
            """
        )
    )

    # ===== §6.3 item =====
    # FK escrow_run_id → dungeon_runs добавим в миграции 0008.
    op.execute(
        sa.DDL(
            """
            CREATE TABLE item (
                id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                owner_profile_id    BIGINT       NOT NULL,
                base_id             BIGINT       NOT NULL,
                rarity              SMALLINT     NOT NULL,
                ilvl                INT          NOT NULL,
                affixes             JSONB        NOT NULL DEFAULT '[]'::jsonb,
                equipped_on         BIGINT,
                equipped_slot       SMALLINT,
                inventory_position  INT,
                is_in_market_escrow BOOLEAN      NOT NULL DEFAULT false,
                escrow_run_id       UUID,
                created_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
                updated_at          TIMESTAMPTZ  NOT NULL DEFAULT now(),
                CONSTRAINT fk_item_profile FOREIGN KEY (owner_profile_id)
                    REFERENCES profile(id),
                CONSTRAINT fk_item_base FOREIGN KEY (base_id)
                    REFERENCES item_base(id),
                CONSTRAINT fk_item_hero FOREIGN KEY (equipped_on)
                    REFERENCES hero(id),
                CONSTRAINT ck_item_rarity      CHECK (rarity BETWEEN 0 AND 4),
                CONSTRAINT ck_item_ilvl_pos    CHECK (ilvl >= 1),
                CONSTRAINT ck_item_equip_slot  CHECK (
                    equipped_slot IS NULL OR equipped_slot BETWEEN 0 AND 5
                ),
                -- Если equipped_on не NULL — слот обязателен; и наоборот.
                CONSTRAINT ck_item_equip_pair  CHECK (
                    (equipped_on IS NULL AND equipped_slot IS NULL)
                    OR (equipped_on IS NOT NULL AND equipped_slot IS NOT NULL)
                ),
                -- inventory_position 0..47 (6×8 grid в MVP).
                CONSTRAINT ck_item_inv_pos CHECK (
                    inventory_position IS NULL
                    OR (inventory_position BETWEEN 0 AND 47)
                ),
                -- Item не может быть одновременно в инвентаре И equipped/escrow.
                CONSTRAINT ck_item_state_exclusive CHECK (
                    (CASE WHEN equipped_on IS NOT NULL THEN 1 ELSE 0 END
                   + CASE WHEN inventory_position IS NOT NULL THEN 1 ELSE 0 END
                   + CASE WHEN is_in_market_escrow THEN 1 ELSE 0 END
                   + CASE WHEN escrow_run_id IS NOT NULL THEN 1 ELSE 0 END
                    ) <= 1
                )
            );
            """
        )
    )
    # Один предмет на слот персонажа.
    op.execute(
        sa.DDL(
            """
            CREATE UNIQUE INDEX uq_item_equipment_slot
                ON item (equipped_on, equipped_slot)
                WHERE equipped_on IS NOT NULL;
            """
        )
    )
    # Один предмет на ячейку инвентаря.
    op.execute(
        sa.DDL(
            """
            CREATE UNIQUE INDEX uq_item_inventory_position
                ON item (owner_profile_id, inventory_position)
                WHERE inventory_position IS NOT NULL;
            """
        )
    )
    # Hot path: предметы юзера в инвентаре (filter NOT escrow).
    op.execute(
        sa.DDL(
            """
            CREATE INDEX ix_item_owner ON item (owner_profile_id)
                WHERE NOT is_in_market_escrow AND escrow_run_id IS NULL;
            """
        )
    )
    op.execute(
        sa.DDL(
            """
            CREATE INDEX ix_item_owner_equipped
                ON item (owner_profile_id, equipped_on)
                WHERE equipped_on IS NOT NULL;
            """
        )
    )
    op.execute(sa.DDL("CREATE INDEX ix_item_rarity ON item (rarity);"))
    op.execute(
        sa.DDL(
            """
            CREATE INDEX ix_item_escrow_run ON item (escrow_run_id)
                WHERE escrow_run_id IS NOT NULL;
            """
        )
    )
    # GIN для маркетного поиска по аффиксам.
    op.execute(
        sa.DDL(
            """
            CREATE INDEX ix_item_affixes_gin
                ON item USING gin (affixes jsonb_path_ops);
            """
        )
    )

    # updated_at trigger (функция уже создана в 0001).
    op.execute(
        sa.DDL(
            """
            CREATE TRIGGER trg_item_updated_at
                BEFORE UPDATE ON item
                FOR EACH ROW EXECUTE FUNCTION trg_set_updated_at();
            """
        )
    )


def downgrade() -> None:
    op.execute("DROP TRIGGER IF EXISTS trg_item_updated_at ON item;")
    op.execute("DROP TABLE IF EXISTS item CASCADE;")
    op.execute("DROP TABLE IF EXISTS affix_definition CASCADE;")
    op.execute("DROP TABLE IF EXISTS item_base CASCADE;")
